# TODO: Fetch base list of tickers and build COINS from that
COINS = {
    "xrp": "XRP",
    "ripple": "XRP",
    "btc": "BTC",
    "bitcoin": "BTC",
    "doge": "DOGE",
    "dogecoin": "DOGE",
    "eth": "ETH",
    "ethereum": "ETH",
    "etc": "ETC",
    "ethereum classic": "ETC",
    "trx": "TRX",
    "tron": "TRX",
    "bat": "BAT",
    "basic attention token": "BAT",
    "btt": "BTT",
    "bittorrent Token": "BTT",
    "usdt": "USDT",
    "wrx": "WRX",
    "wazirx token": "WRX",
    "matic": "MATIC",
    "matic network": "MATIC",
    "ada": "ADA",
    "cardano": "ADA",
    "dash": "DASH",
    "omg": "OMG",
    "omise go": "OMG",
    "omisego": "OMG",
    "vet": "VET",
    "ve chain": "VET",
    "vechain": "VET",
}
